# .github/workflows/mirror-to-public.yml

name: Mirror to Public Repo (kaiju_trial)

# This allows you to run this workflow manually from the Actions tab
on:
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the source private repository completely
      - name: Checkout source repository (RealmeC21Y-kernelSU-Next-susfs4)
        uses: actions/checkout@v4
        with:
          # This fetches all history for all branches and tags, which is crucial for a mirror.
          fetch-depth: 0

      # Step 2: Push everything to the public destination repository
      - name: Push to public repository (kaiju_trial)
        run: |
          echo "Mirroring to https://github.com/fanu96/kaiju_trial.git"
          # Use the --mirror flag to copy all branches, tags, and history.
          # The secret provides the authentication needed to push to the destination repo.
          git push --mirror "https://${{ secrets.BACKUP_PAT }}@github.com/fanu96/kaiju_trial.git"
