# .github/workflows/mirror.yml

name: Mirror to kaiju_trial

# This allows you to run this workflow manually from the Actions tab
on:
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the source repository (this one) completely
      - name: Checkout source repository
        uses: actions/checkout@v4
        with:
          # This fetches all history for all branches and tags, which is crucial for a mirror
          fetch-depth: 0

      # Step 2: Push everything to the new repository
      - name: Push to new repository (kaiju_trial)
        run: |
          echo "Mirroring to https://github.com/fanu96/kaiju_trial.git"
          # Use the --mirror flag to copy all branches, tags, and history
          # The secret provides the authentication needed to push to the private repo
          git push --mirror "https://${{ secrets.BACKUP_PAT }}@github.com/fanu96/kaiju_trial.git"
