name: Debug Secret Checker

on:
  workflow_dispatch:

jobs:
  check-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Check if the secret exists
        run: |
          if [ -n "${{ secrets.BACKUP_PAT }}" ]; then
            echo "✅ Success: The BACKUP_PAT secret was loaded by the runner."
          else
            echo "❌ Failure: The BACKUP_PAT secret is EMPTY or NOT FOUND."
            exit 1
          fi

      - name: Check the first few characters of the token (SAFE)
        run: |
          # This is a safe way to confirm the token format without exposing it.
          # A classic PAT starts with ghp_
          TOKEN_VALUE="${{ secrets.BACKUP_PAT }}"
          if [[ $TOKEN_VALUE == ghp_* ]]; then
            echo "✅ Success: The secret appears to be a classic PAT (starts with ghp_)."
          else
            echo "❌ Failure: The secret does NOT look like a classic PAT."
            exit 1
          fi
