# .github/workflows/mirror-to-public.yml

name: Mirror to Public Repo (kaiju_trial)

on:
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the source repository
      - name: Checkout source repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetches all history for all branches and tags

      # Step 2: Set up the SSH key for authentication
      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY_PRIVATE }}

      # Step 3: Push to the destination repository using SSH
      - name: Push to public repository
        run: |
          echo "Pushing to the destination repository..."
          # We use the SSH URL format now because we are authenticating with a deploy key.
          git push --mirror git@github.com:fanu96/kaiju_trial.git
